language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
script:
- python -m unittest discover
deploy:
  provider: pypi
  skip_existing: true
  user: janhartigan
  password:
    secure: sNEuqEQr6hdwE7fsRIcwkhEfY/lYPG72bN0TkKhGsSe1SZuLyaht3+5CPcbHW664piPvVgRZQw+vhKm+/U92qRHx4n7W58gD6M1giOAfeLVgu+l2I5VLKyZPcPXdNJAMLHwXzOVHKQ//Ia9BLXfiyDTqISHPPltyaJW2pJEZb24F/0J7i2icPxCWKWvJQZEV5zar6SPedq/M1wqZWkqruLgZ2Mv7WtxGZctlNPCPy4skp5PTx/DZIZvVfRBdOC8OyuU6+rs41+kY1sPbHwa62kfa/jkLFYDq+svRSaqfyXYxUaMWDtH/sSawyujlxOoGEtLZvBjl+C6dFRs5M0o4ZPgIWUqtYhlGIXlbSQVBiP0vOXzSxxlB95LraMwfz+mRpc39bhFwZIEhCvqEqo2IpNTs1/6kmCk6g1l7RDVqv95rWQjJQRraw3LKfl1/hsmdlpY/nyADaKePZZuuF6Lo+zLX4OVLwHVWnYPpw4Gmz7TDzvQbz/ZkIPB51uwgqpPLUBPkRp4YBcMU7z0EHMflelH+3OczbY8jbZwkqX0rVcE0DyG9fA9HN6pNXyHxJfQ3TxsQaYzeqW6pDZceCK3xJugCj1/0oJokYZAsu63u4qgO5yHLpYA7nE8L1qmvUiHh+aA0hjAJ54L1YpMdONlduhRDuyqRRK/kKzqR06+lAY0=
  on:
    tags: true
notifications:
  email:
    on_success: change