language: python
python:
- '3.4'
- '3.5'
- '3.6'
script:
- python -m unittest discover
deploy:
  provider: pypi
  skip_existing: true
  user: janhartigan
  password:
    secure: WTqAFsAahtvSIrAvJrIJVAaYrjQKhsjZPAknSfgjq5ix5/yAmcahVpQyjtKFC0k/s+EjqfsWLsN6KmHf33u9G9PvbQK3OvW67/DAg/uf+SG0BUf5EvISDWvL3MNv6UiJlKxHCQFUvWA6Y6wfPlybl+dVAygxwF8ixXYk/bI/QwetGbOULMjpdk9CF5dc4ylaUb/MSTJfyS/ypHHyz3A+2EOWzIVZbYWbch0e/hPo5xUI51jN+xTlA1gJpR9U1RG9y/1U67TTX2E1tjzURc9jZgPgSaoutyYz/dpQoBAFCAEHf9JOfoBYG10lhDIlQ2+Ij4PIGRIFOGrIc4Qy+qL06dvjmL/ZH9YIdHnd8WjfdkeqTMjRqdlO3+T+ZUFuya4onM/EaaiaFDfzFVg1idkFtw0FMTQY7JJb35ZnaBrsqnsjXSSeHyfTK9eNceuv9UTW7sq3Je8T52AZ2sx6ywMLk9Nd1/r7Qpu+6EW6IiGRX1IsgxCpDGbsHBTpDEieNHiHum9fTAEgs8mSVzeHwlNLEtfpkJkeE5Ze08YJ3NT4nFkcrelctyPg16ebCVij19zw4BAff/KBferRdGGLbaZRLFf2YnoAutPnNerWfdlmApjsHSDZhHRMru5oZaPc59vT57qN6nUTBmzM4JLMP/HyNY8JLVWIoA0/pnIRwcAxL64=
  on:
    tags: true
notifications:
  email:
    on_success: change